import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'github-markdown-css/github-markdown-light.css'
import 'katex/dist/katex.min.css';
import Navi from "@/components/Navigation";
import Footer from "@/components/Footer";
import { getAllPostData } from "@/lib/posts";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
 
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
 
export const metadata: Metadata = {
  icons:{
      icon: "https://avatars.githubusercontent.com/u/161662653?v=4" // 이미지 주소
  },
  title: "개발블로그",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const postsData = getAllPostData();
 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="print:hidden">
          <Navi posts={postsData} />
        </div>
        {children}
        <div className="print:hidden">
          <Footer />
        </div>
      </body>
    </html>
  );
}
 